import type { Artist, BridalEvent, Category, NonBridalEvent, Studio } from "./types";

export const MALAYSIA_STATES = [
  "Johor",
  "Kedah",
  "Kelantan",
  "Kuala Lumpur",
  "Labuan",
  "Malacca",
  "Negeri Sembilan",
  "Pahang",
  "Penang",
  "Perak",
  "Perlis",
  "Putrajaya",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
] as const;

export type State = (typeof MALAYSIA_STATES)[number];

export const AREAS_BY_STATE: Record<State, string[]> = {
  Selangor: [
    "Cyberjaya",
    "Subang Jaya",
    "Petaling Jaya",
    "Shah Alam",
    "Klang",
    "Ampang",
    "Bangi",
    "Puchong",
    "Damansara",
    "Rawang",
    "Sepang",
    "Serdang",
  ],
  "Kuala Lumpur": [
    "KLCC",
    "Bukit Bintang",
    "Mont Kiara",
    "Bangsar",
    "Cheras",
    "Setapak",
    "Wangsa Maju",
    "Kepong",
    "Damansara Heights",
    "Taman Desa",
  ],
  Johor: [
    "Pasir Gudang",
    "Johor Bahru",
    "Skudai",
    "Iskandar Puteri",
    "Kulai",
    "Batu Pahat",
    "Muar",
    "Kluang",
  ],
  Penang: ["George Town", "Bayan Lepas", "Butterworth", "Tanjung Bungah", "Gurney", "Balik Pulau"],
  Perak: ["Ipoh", "Taiping", "Teluk Intan", "Sitiawan", "Kampar"],
  Malacca: ["Bandar Melaka", "Ayer Keroh", "Bukit Baru", "Bachang"],
  "Negeri Sembilan": ["Seremban", "Port Dickson", "Nilai", "Senawang"],
  Pahang: ["Kuantan", "Temerloh", "Bentong", "Cameron Highlands"],
  Kedah: ["Alor Setar", "Sungai Petani", "Kulim", "Langkawi"],
  Kelantan: ["Kota Bharu", "Pasir Mas", "Tanah Merah", "Bachok"],
  Terengganu: ["Kuala Terengganu", "Kemaman", "Dungun", "Marang"],
  Perlis: ["Kangar", "Arau", "Padang Besar"],
  Putrajaya: ["Presint 1", "Presint 9", "Presint 15", "Presint 16"],
  Labuan: ["Bandar Labuan", "Kiamsam", "Victoria"],
  Sabah: ["Kota Kinabalu", "Sandakan", "Tawau", "Penampang"],
  Sarawak: ["Kuching", "Miri", "Sibu", "Bintulu", "Samarahan"],
};

export const BRIDAL_EVENTS: { id: BridalEvent; label: string }[] = [
  { id: "engagement", label: "Engagement" },
  { id: "solemnization", label: "Solemnization" },
  { id: "reception", label: "Reception" },
  { id: "full-package", label: "Full Package (Engagement + Solemnization + Reception)" },
  { id: "bridal-other", label: "Other" },
];

export const NON_BRIDAL_EVENTS: { id: NonBridalEvent; label: string }[] = [
  { id: "dinner", label: "Dinner" },
  { id: "graduation", label: "Graduation" },
  { id: "ceremony", label: "Ceremony" },
  { id: "corporate", label: "Corporate" },
  { id: "touch-up", label: "Touch-up" },
  { id: "non-bridal-other", label: "Other" },
];

export const CATEGORIES: Category[] = [
  {
    slug: "bridal",
    name: "Bridal Makeup",
    description: "Engagement, solemnization, reception & full wedding packages",
    image: "/images/hero.jpg",
    count: 8,
  },
  {
    slug: "engagement",
    name: "Engagement",
    description: "Natural glam for your special photoshoot moments",
    image: "/images/artist-5.jpg",
    count: 6,
  },
  {
    slug: "graduation",
    name: "Graduation & Events",
    description: "Capsule glam, dinners and celebration-ready looks",
    image: "/images/artist-2.jpg",
    count: 5,
  },
  {
    slug: "corporate",
    name: "Corporate",
    description: "Polished, professional looks for work and functions",
    image: "/images/artist-6.jpg",
    count: 4,
  },
];

export const ARTISTS: Artist[] = [
  {
    id: "aisha-azman",
    name: "Aisha Azman",
    tagline: "Bridal couture artist · 10 years of making brides glow",
    bio: "Aisha is one of KL's most sought-after bridal makeup artists, known for soft-glam finishes that photograph beautifully from every angle. She has styled brides across Malaysia and Singapore and specialises in elegant, long-wear bridal looks.",
    image: "/images/artist-1.jpg",
    rating: 4.9,
    reviewCount: 182,
    state: "Selangor",
    area: "Cyberjaya",
    priceFrom: 680,
    specialties: ["Bridal", "Soft Glam", "Airbrush", "HD Makeup"],
    services: [
      { name: "Engagement Makeup", price: 480, duration: "1.5 hrs" },
      { name: "Solemnization Makeup", price: 580, duration: "2 hrs" },
      { name: "Reception Makeup", price: 680, duration: "2.5 hrs" },
      { name: "Full Bridal Package", price: 2880, duration: "Full day" },
    ],
    bridal: ["engagement", "solemnization", "reception", "full-package"],
    nonBridal: ["touch-up", "dinner"],
    availability: ["Tomorrow, 10:00 AM", "Tomorrow, 3:00 PM", "Sat, 10:00 AM"],
    portfolio: ["/images/artist-1.jpg", "/images/hero.jpg", "/images/artist-5.jpg"],
    verified: true,
    yearsExperience: 10,
    reviews: [
      { id: "r1", author: "Nurul H.", rating: 5, date: "Jun 2026", event: "Full Bridal Package", text: "Aisha made me look like the best version of myself on my wedding day. Makeup lasted 14 hours with zero touch-ups needed!" },
      { id: "r2", author: "Priya K.", rating: 5, date: "May 2026", event: "Solemnization", text: "Super professional, punctual, and so sweet. The soft glam look was exactly what I asked for." },
      { id: "r3", author: "Sarah L.", rating: 4.5, date: "Apr 2026", event: "Engagement", text: "Beautiful work and great communication. Booking was instant and easy." },
    ],
  },
  {
    id: "maya-tan",
    name: "Maya Tan",
    tagline: "Editorial glam for events, grad & corporate",
    bio: "Maya blends editorial trends with everyday wearability. A former beauty editor, she now runs her own studio and travels to clients across the Klang Valley for dinners, graduations and corporate events.",
    image: "/images/artist-2.jpg",
    rating: 4.8,
    reviewCount: 96,
    state: "Kuala Lumpur",
    area: "Bangsar",
    priceFrom: 350,
    specialties: ["Editorial", "Soft Glam", "Smokey Eyes", "HD Makeup"],
    services: [
      { name: "Graduation Makeup", price: 350, duration: "1.5 hrs" },
      { name: "Dinner / Event Makeup", price: 380, duration: "1.5 hrs" },
      { name: "Corporate Makeup", price: 300, duration: "1 hr" },
      { name: "Touch-up Package", price: 150, duration: "45 min" },
    ],
    bridal: ["bridal-other"],
    nonBridal: ["dinner", "graduation", "corporate", "touch-up"],
    availability: ["Tomorrow, 12:00 PM", "Thu, 6:00 PM", "Sat, 2:00 PM"],
    portfolio: ["/images/artist-2.jpg", "/images/artist-6.jpg", "/images/artist-4.jpg"],
    verified: true,
    yearsExperience: 7,
    reviews: [
      { id: "r1", author: "Wei Ming", rating: 5, date: "Jul 2026", event: "Graduation", text: "Maya did my sister's grad makeup and she got compliments all day. So natural yet camera-ready." },
      { id: "r2", author: "Dina S.", rating: 4.5, date: "Jun 2026", event: "Corporate", text: "Punctual, professional and the look was polished without being heavy. Perfect for the office." },
    ],
  },
  {
    id: "sofia-rahim",
    name: "Sofia Rahim",
    tagline: "Airbrush perfectionist for brides & beyond",
    bio: "Sofia is an airbrush makeup specialist with a loyal following in Johor. Her feather-light technique delivers flawless, photo-proof skin that lasts all day, even under Malaysia's heat.",
    image: "/images/artist-3.jpg",
    rating: 5.0,
    reviewCount: 143,
    state: "Johor",
    area: "Pasir Gudang",
    priceFrom: 520,
    specialties: ["Airbrush", "Bridal", "Flawless Base", "HD Makeup"],
    services: [
      { name: "Engagement Makeup", price: 450, duration: "1.5 hrs" },
      { name: "Solemnization Makeup", price: 520, duration: "2 hrs" },
      { name: "Reception Makeup", price: 620, duration: "2.5 hrs" },
      { name: "Full Bridal Package", price: 2480, duration: "Full day" },
    ],
    bridal: ["engagement", "solemnization", "reception", "full-package"],
    nonBridal: ["ceremony", "dinner"],
    availability: ["Tomorrow, 9:00 AM", "Fri, 11:00 AM", "Sun, 10:00 AM"],
    portfolio: ["/images/artist-3.jpg", "/images/hero.jpg", "/images/artist-5.jpg"],
    verified: true,
    yearsExperience: 8,
    reviews: [
      { id: "r1", author: "Farah Z.", rating: 5, date: "Jul 2026", event: "Reception", text: "The airbrush base was unreal. My skin looked perfect in every single photo." },
      { id: "r2", author: "Iman A.", rating: 5, date: "May 2026", event: "Engagement", text: "Sofia came to our home in Pasir Gudang early, calm and prepared. Loved the whole experience." },
    ],
  },
  {
    id: "jason-lee",
    name: "Jason Lee",
    tagline: "Men's grooming & editorial makeup artist",
    bio: "One of the few specialised male grooming artists in the Klang Valley, Jason works with brands, TV talent and grooms-to-be. Clean, sharp, camera-ready looks — every time.",
    image: "/images/artist-4.jpg",
    rating: 4.7,
    reviewCount: 58,
    state: "Selangor",
    area: "Petaling Jaya",
    priceFrom: 280,
    specialties: ["Groom Makeup", "Editorial", "Sharp Contour", "HD Makeup"],
    services: [
      { name: "Groom Makeup", price: 380, duration: "1.5 hrs" },
      { name: "Editorial / Photo Shoot", price: 280, duration: "1 hr" },
      { name: "Corporate / TV", price: 300, duration: "1 hr" },
    ],
    bridal: [],
    nonBridal: ["ceremony", "corporate", "dinner"],
    availability: ["Tomorrow, 2:00 PM", "Thu, 10:00 AM", "Sat, 9:00 AM"],
    portfolio: ["/images/artist-4.jpg", "/images/artist-6.jpg"],
    verified: true,
    yearsExperience: 6,
    reviews: [
      { id: "r1", author: "Daniel G.", rating: 5, date: "Jun 2026", event: "Groom Makeup", text: "Kept me looking natural but polished for the wedding. My wife approved!" },
      { id: "r2", author: "TV Producer KL", rating: 4.5, date: "May 2026", event: "Corporate", text: "Reliable on set, great with last-minute changes." },
    ],
  },
  {
    id: "nur-fatin",
    name: "Nur Fatin",
    tagline: "Soft glam & natural beauty · Penang",
    bio: "Fatin is a Penang-based artist known for dewy, natural beauty looks. She specialises in engagement and graduation makeup and loves working with first-time brides.",
    image: "/images/artist-5.jpg",
    rating: 4.8,
    reviewCount: 74,
    state: "Penang",
    area: "George Town",
    priceFrom: 320,
    specialties: ["Natural", "Dewy Skin", "Soft Glam", "Bridal"],
    services: [
      { name: "Engagement Makeup", price: 380, duration: "1.5 hrs" },
      { name: "Graduation Makeup", price: 320, duration: "1.5 hrs" },
      { name: "Dinner Makeup", price: 350, duration: "1.5 hrs" },
    ],
    bridal: ["engagement", "solemnization"],
    nonBridal: ["graduation", "dinner", "touch-up"],
    availability: ["Tomorrow, 11:00 AM", "Fri, 3:00 PM", "Sun, 1:00 PM"],
    portfolio: ["/images/artist-5.jpg", "/images/artist-3.jpg", "/images/artist-2.jpg"],
    verified: false,
    yearsExperience: 5,
    reviews: [
      { id: "r1", author: "Carmen O.", rating: 5, date: "Jul 2026", event: "Graduation", text: "Dewy, fresh and gorgeous. Fatin is so easy to talk to." },
      { id: "r2", author: "Li Yin", rating: 4.5, date: "Apr 2026", event: "Engagement", text: "Lovely soft look, exactly what I wanted for our photoshoot." },
    ],
  },
  {
    id: "hana-mustafa",
    name: "Hana Mustafa",
    tagline: "Classic glam, modern execution · Cyberjaya",
    bio: "Hana creates timeless classic glam looks with a modern twist. From solemnization to corporate functions, her work is elegant, polished and always on time.",
    image: "/images/artist-6.jpg",
    rating: 4.9,
    reviewCount: 67,
    state: "Selangor",
    area: "Cyberjaya",
    priceFrom: 300,
    specialties: ["Classic Glam", "Bridal", "Corporate", "HD Makeup"],
    services: [
      { name: "Solemnization Makeup", price: 480, duration: "2 hrs" },
      { name: "Corporate Makeup", price: 280, duration: "1 hr" },
      { name: "Dinner Makeup", price: 330, duration: "1.5 hrs" },
      { name: "Touch-up Package", price: 120, duration: "45 min" },
    ],
    bridal: ["solemnization", "reception"],
    nonBridal: ["corporate", "dinner", "touch-up", "ceremony"],
    availability: ["Tomorrow, 4:00 PM", "Thu, 12:00 PM", "Sat, 5:00 PM"],
    portfolio: ["/images/artist-6.jpg", "/images/artist-4.jpg", "/images/hero.jpg"],
    verified: true,
    yearsExperience: 6,
    reviews: [
      { id: "r1", author: "Aina R.", rating: 5, date: "Jun 2026", event: "Solemnization", text: "Timeless, elegant, and she was so reassuring on the day." },
    ],
  },
  {
    id: "devi-ramasamy",
    name: "Devi Ramasamy",
    tagline: "Bridal & traditional event specialist · Ipoh",
    bio: "Devi is a Perak favourite for traditional and bridal occasions, fluent in multiple bridal traditions with over a decade of experience styling families for big days.",
    image: "/images/artist-3.jpg",
    rating: 4.8,
    reviewCount: 121,
    state: "Perak",
    area: "Ipoh",
    priceFrom: 420,
    specialties: ["Traditional", "Bridal", "Airbrush", "Family Packages"],
    services: [
      { name: "Engagement Makeup", price: 420, duration: "1.5 hrs" },
      { name: "Reception Makeup", price: 580, duration: "2.5 hrs" },
      { name: "Family Group Package", price: 980, duration: "Half day" },
    ],
    bridal: ["engagement", "reception", "full-package"],
    nonBridal: ["ceremony"],
    availability: ["Fri, 10:00 AM", "Sun, 9:00 AM"],
    portfolio: ["/images/artist-3.jpg", "/images/hero.jpg"],
    verified: true,
    yearsExperience: 12,
    reviews: [
      { id: "r1", author: "Kavitha M.", rating: 5, date: "May 2026", event: "Full Bridal Package", text: "Devi styled my whole family for my wedding. Everyone looked incredible." },
    ],
  },
];

export const STUDIOS: Studio[] = [
  {
    id: "glow-room-cyberjaya",
    name: "The Glow Room",
    tagline: "A serene beauty studio in the heart of Cyberjaya",
    description:
      "The Glow Room offers premium bridal trials, express glam and lash services in a calm, private setting. Home to Aisha Azman and a handpicked team of artists.",
    image: "/images/studio-1.jpg",
    rating: 4.9,
    reviewCount: 210,
    state: "Selangor",
    area: "Cyberjaya",
    address: "12-G, Jalan Teknokrat 5, Cyber 5, 63000 Cyberjaya, Selangor",
    services: ["Bridal Trials", "Express Glam", "Lash Extensions", "Brows & Waxing", "Airbrush Makeup"],
    priceFrom: 180,
    hours: "10:00 AM – 8:00 PM daily",
    phone: "03-8318 2200",
  },
  {
    id: "bangsar-beauty-bar",
    name: "Bangsar Beauty Bar",
    tagline: "Editorial-grade glam in KL's creative hub",
    description:
      "Founded by Maya Tan, Bangsar Beauty Bar is a modern studio loved by creatives, graduates and corporate clients for sharp, trend-forward looks.",
    image: "/images/studio-2.jpg",
    rating: 4.8,
    reviewCount: 156,
    state: "Kuala Lumpur",
    area: "Bangsar",
    address: "28, Jalan Telawi 3, Bangsar, 59100 Kuala Lumpur",
    services: ["Event Makeup", "Editorial", "Lash & Brow Bar", "Skincare Facials", "Hair Styling"],
    priceFrom: 150,
    hours: "11:00 AM – 9:00 PM (Tue–Sun)",
    phone: "03-2201 8830",
  },
  {
    id: "jb-glam-studio",
    name: "JB Glam Studio",
    tagline: "Airbrush specialists serving Johor Bahru & Pasir Gudang",
    description:
      "JB Glam Studio is Johor's home of airbrush makeup, led by Sofia Rahim. Bridal packages include trials, on-location service and full-day support.",
    image: "/images/studio-3.jpg",
    rating: 4.9,
    reviewCount: 188,
    state: "Johor",
    area: "Johor Bahru",
    address: "77, Jalan Serantau, Taman Daya, 81100 Johor Bahru, Johor",
    services: ["Bridal Packages", "Airbrush Makeup", "Manicure & Pedicure", "Hair Styling", "On-location Service"],
    priceFrom: 200,
    hours: "10:00 AM – 7:00 PM daily",
    phone: "07-357 2200",
  },
  {
    id: "georgetown-glams",
    name: "George Town Glams",
    tagline: "Heritage charm meets modern beauty in Penang",
    description:
      "A boutique studio in a restored shophouse, George Town Glams specialises in natural, dewy looks for graduations, engagements and special occasions.",
    image: "/images/studio-1.jpg",
    rating: 4.7,
    reviewCount: 92,
    state: "Penang",
    area: "George Town",
    address: "45, Lebuh Armenian, 10200 George Town, Penang",
    services: ["Graduation Makeup", "Engagement Makeup", "Brows & Lashes", "Facials", "Hair Styling"],
    priceFrom: 160,
    hours: "11:00 AM – 7:00 PM (Mon–Sat)",
    phone: "04-261 4450",
  },
];

export function getArtist(id: string): Artist | undefined {
  return ARTISTS.find((a) => a.id === id);
}

export function getStudio(id: string): Studio | undefined {
  return STUDIOS.find((s) => s.id === id);
}
