import type { Product } from "./types";

export const BEAUTY_PRODUCTS: Product[] = [
  {
    id: "k-bean-essence",
    name: "K-Beauty Essence Serum",
    slug: "k-beauty-essence-serum",
    description: "Lightweight hydrating serum with fermented extracts for radiant skin",
    price: 4200,
    category: "skincare",
    brand: "Seoul Secrets",
    image_url: "/products/k-bean-essence.jpg",
    rating: 4.8,
    review_count: 342,
    is_featured: true,
    stock_count: 45,
    min_order: 1,
    return_policy: "30-day satisfaction guarantee",
    ingredients: "Fermented rice water, hyaluronic acid, green tea extract",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 1,
  },
  {
    id: "malaysian-glow-oil",
    name: "Malaysian Glow Facial Oil",
    slug: "malaysian-glow-facial-oil",
    description: "Cold-pressed tropical botanical oil for dewy, luminous complexion",
    price: 3800,
    category: "skincare",
    brand: "Tropical Beauty",
    image_url: "/products/malaysian-glow-oil.jpg",
    rating: 4.6,
    review_count: 218,
    is_featured: false,
    stock_count: 62,
    min_order: 1,
    return_policy: "30-day satisfaction guarantee",
    ingredients: "Coconut oil, patchouli, lemongrass, vitamin E",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 2,
  },
  {
    id: "bamboo-hair-mask",
    name: "Bamboo Hair Repair Mask",
    slug: "bamboo-hair-mask",
    description: "Intensive repair treatment for damaged hair with bamboo extract",
    price: 2800,
    category: "haircare",
    brand: "Kligence Hair",
    image_url: "/products/bamboo-hair-mask.jpg",
    rating: 4.7,
    review_count: 189,
    is_featured: false,
    stock_count: 38,
    min_order: 1,
    return_policy: "30-day satisfaction guarantee",
    ingredients: "Bamboo extract, keratin, argan oil, aloe vera",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 3,
  },
  {
    id: "21st-century-lipstick",
    name: "21st Century Liquid Lipstick",
    slug: "21st-century-liquid-lipstick",
    description: "Long-wear matte lip color with comfortable, transfer-proof formula",
    price: 3200,
    category: "makeup",
    brand: "Urban Velvet",
    image_url: "/products/21st-century-liquid-lipstick.jpg",
    rating: 4.9,
    review_count: 415,
    is_featured: true,
    stock_count: 89,
    min_order: 1,
    return_policy: "30-day satisfaction guarantee",
    ingredients: "Jojoba oil, vitamin E, synthetic beeswax alternative",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 4,
  },
  {
    id: "malaysian-henna-set",
    name: "Traditional Malaysian Henna Set",
    slug: "malaysian-henna-set",
    description: "Natural henna for intricate bridal and festival body art",
    price: 1800,
    category: "beauty-accessories",
    brand: "Heritage Art",
    image_url: "/products/malaysian-henna-set.jpg",
    rating: 4.8,
    review_count: 156,
    is_featured: false,
    stock_count: 23,
    min_order: 1,
    return_policy: "Store credit within 14 days",
    ingredients: "Natural henna leaf powder, essential oils (lavender, eucalyptus)",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 5,
  },
  {
    id: "brow-definition-pen",
    name: "Precision Brow Definition Pen",
    slug: "precision-brow-definition-pen",
    description: "Waterproof brow pencil for natural-to-bold looks with fine tip",
    price: 2500,
    category: "makeup",
    brand: "Define&Co",
    image_url: "/products/brow-definition-pen.jpg",
    rating: 4.5,
    review_count: 278,
    is_featured: false,
    stock_count: 71,
    min_order: 1,
    return_policy: "30-day satisfaction guarantee",
    ingredients: "Castor oil, jojoba wax, vitamin E, pigment",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 6,
  },
  {
    id: "24k-gold-face-mask",
    name: "24K Gold Hydrating Face Mask",
    slug: "24k-gold-face-mask",
    description: "Luxury sheet mask with 24K gold flakes for instant radiance",
    price: 5500,
    category: "skincare",
    brand: "Golden Radiance",
    image_url: "/products/24k-gold-face-mask.jpg",
    rating: 4.4,
    review_count: 123,
    is_featured: false,
    stock_count: 15,
    min_order: 1,
    return_policy: "7-day satisfaction guarantee",
    ingredients: "24K gold flakes, hyaluronic acid, collagen, pearl extract",
    is_clean: false,
    is_cruelty_free: false,
    sort_order: 7,
  },
  {
    id: "natural-foundation",
    name: "Natural Finish Foundation",
    slug: "natural-foundation",
    description: "Buildable coverage foundation that looks like skin, 12 shade range",
    price: 4800,
    category: "makeup",
    brand: "PureCanvas",
    image_url: "/products/natural-foundation.jpg",
    rating: 4.7,
    review_count: 389,
    is_featured: true,
    stock_count: 53,
    min_order: 1,
    return_policy: "30-day satisfaction guarantee",
    ingredients: "Aloe vera, jojoba oil, vitamin E, mineral pigments",
    is_clean: true,
    is_cruelty_free: true,
    sort_order: 8,
  },
];

export function getProduct(id: string): Product | undefined {
  return BEAUTY_PRODUCTS.find((p) => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return BEAUTY_PRODUCTS.filter((p) => p.is_featured);
}

export function getProductsByCategory(category: string): Product[] {
  return BEAUTY_PRODUCTS.filter((p) => p.category === category);
}

export function getProductsByBrand(brand: string): Product[] {
  return BEAUTY_PRODUCTS.filter((p) => p.brand === brand);
}